name: Update README
on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:
jobs:
  build:
    name: Update this repo's README with recent activity
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: GitHub - Activity - Readme       
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@v0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          GH_USERNAME: Nuellity
          COMMIT_MSG: Update README with the recent activity
          MAX_LINES: 5
          COMMIT_NAME: github-actions[bot]
          TARGET_FILE: README.md
          COMMIT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
